version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    container_name: trading-bot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backtesting/outputs:/app/backtesting/outputs
      - ./logs:/app/logs
      - ./backtesting/csv_input:/app/backtesting/csv_input
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - trading-bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: trading-bot-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - trading-bot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  trading-bot-network:
    driver: bridge

volumes:
  backtest-outputs:
    driver: local
  logs:
    driver: local