version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    container_name: trading-bot-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./backtesting/outputs:/app/backtesting/outputs
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - API_RELOAD=true
    env_file:
      - .env.dev
    restart: unless-stopped
    networks:
      - trading-bot-network
    command: ["python", "-m", "uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: trading-bot-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - trading-bot-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  trading-bot-network:
    driver: bridge