// Mock data to use when API calls fail or during development
import { MarketData } from '../store/slices/dataSlice';
import { Strategy } from '../store/slices/strategySlice';
import { BacktestResult } from '../store/slices/backtestingSlice';

// Mock available market data
export const mockAvailableData: MarketData[] = [
  {
    id: '1',
    symbol: 'AAPL',
    timeframe: '1d',
    startDate: '2022-05-02',
    endDate: '2022-05-31',
    recordCount: 252,
    source: 'csv',
    hasIndicators: true,
    fileSize: '52KB',
    lastUpdated: '2024-04-15',
  },
  {
    id: '2',
    symbol: 'MSFT',
    timeframe: '1d',
    startDate: '2023-01-01',
    endDate: '2024-01-01',
    recordCount: 252,
    source: 'csv',
    hasIndicators: true,
    fileSize: '48KB',
    lastUpdated: '2024-04-15',
  },
  {
    id: '3',
    symbol: 'TSLA',
    timeframe: '1d',
    startDate: '2023-01-01',
    endDate: '2024-01-01',
    recordCount: 252,
    source: 'csv',
    hasIndicators: false,
    fileSize: '50KB',
    lastUpdated: '2024-04-15',
  },
];

// Mock symbols
export const mockSymbols = ['AAPL', 'MSFT', 'TSLA', 'GOOGL', 'AMZN', 'META', 'NVDA'];

// Mock strategies
export const mockStrategies: Strategy[] = [
  {
    id: 'moving_average_crossover',
    name: 'Moving Average Crossover',
    description: 'A trend-following strategy that generates buy/sell signals when a fast-moving average crosses a slow-moving average.',
    type: 'template',
    parameters: [
      { name: 'fastPeriod', type: 'number', value: 10, min: 2, max: 50, step: 1 },
      { name: 'slowPeriod', type: 'number', value: 30, min: 5, max: 100, step: 1 },
    ],
    indicators: ['SMA', 'EMA'],
    createdAt: '2024-01-01',
    updatedAt: '2024-05-15',
    status: 'active',
  },
  {
    id: 'rsi_oversold_overbought',
    name: 'RSI Overbought/Oversold',
    description: 'A momentum strategy that uses the Relative Strength Index (RSI) to identify overbought or oversold conditions for potential reversals.',
    type: 'template',
    parameters: [
      { name: 'period', type: 'number', value: 14, min: 5, max: 30, step: 1 },
      { name: 'overbought', type: 'number', value: 70, min: 60, max: 90, step: 5 },
      { name: 'oversold', type: 'number', value: 30, min: 10, max: 40, step: 5 },
    ],
    indicators: ['RSI'],
    createdAt: '2024-01-10',
    updatedAt: '2024-05-10',
    status: 'active',
  },
  {
    id: 'bollinger_bands_mean_reversion',
    name: 'Bollinger Bands Mean Reversion',
    description: 'A volatility-based strategy that assumes prices will revert to the mean after touching the upper or lower Bollinger Bands.',
    type: 'template',
    parameters: [
      { name: 'period', type: 'number', value: 20, min: 10, max: 50, step: 1 },
      { name: 'stdDev', type: 'number', value: 2, min: 1, max: 3, step: 0.5 },
    ],
    indicators: ['Bollinger Bands'],
    createdAt: '2024-02-01',
    updatedAt: '2024-05-01',
    status: 'inactive',
  },
  {
    id: 'macd_crossover',
    name: 'MACD Crossover',
    description: 'A trend-following momentum strategy based on the crossing of the MACD line and its signal line, and their relation to the zero line.',
    type: 'template',
    parameters: [
      { name: 'fastPeriod', type: 'number', value: 12, min: 5, max: 30, step: 1 },
      { name: 'slowPeriod', type: 'number', value: 26, min: 15, max: 60, step: 1 },
      { name: 'signalPeriod', type: 'number', value: 9, min: 5, max: 20, step: 1 },
    ],
    indicators: ['MACD'],
    createdAt: '2024-02-15',
    updatedAt: '2024-04-20',
    status: 'active',
  },
  {
    id: 'arbitrage',
    name: 'Arbitrage',
    description: 'A strategy that seeks to profit from temporary price differences of the same asset on different exchanges or markets.',
    type: 'custom',
    parameters: [],
    indicators: [],
    createdAt: '2024-03-01',
    updatedAt: '2024-04-25',
    status: 'inactive',
  },
  {
    id: 'linear_regression',
    name: 'Linear Regression',
    description: 'Analyzes historical price data to predict future price movements based on a linear trend.',
    type: 'custom',
    parameters: [
      { name: 'period', type: 'number', value: 20, min: 10, max: 100, step: 5 },
    ],
    indicators: ['Linear Regression'],
    createdAt: '2024-03-15',
    updatedAt: '2024-04-10',
    status: 'active',
  },
  {
    id: 'time_based',
    name: 'Time Based',
    description: 'Executes trades based on specific time intervals or market hours, ignoring traditional technical indicators.',
    type: 'custom',
    parameters: [
      { name: 'entryHour', type: 'number', value: 9, min: 0, max: 23, step: 1 },
      { name: 'exitHour', type: 'number', value: 16, min: 0, max: 23, step: 1 },
    ],
    indicators: [],
    createdAt: '2024-02-20',
    updatedAt: '2024-04-05',
    status: 'inactive',
  },
  {
    id: 'each_bar_long_tp_sl_1d_candle',
    name: 'Each-Bar Long TP/SL 1-D Candle',
    description: 'A strategy that executes long trades on each bar, with predefined take-profit and stop-loss levels based on 1-day candle data.',
    type: 'custom',
    parameters: [
      { name: 'takeProfit', type: 'number', value: 1.0, min: 0.1, max: 10, step: 0.1 },
      { name: 'stopLoss', type: 'number', value: 0.5, min: 0.1, max: 10, step: 0.1 },
    ],
    indicators: [],
    createdAt: '2024-05-20',
    updatedAt: '2024-05-20',
    status: 'active',
  },
  {
    id: 'each_bar_long_ma',
    name: 'Each-Bar Long MA',
    description: 'A strategy that initiates long positions on every bar, utilizing moving averages for entry signals.',
    type: 'custom',
    parameters: [
      { name: 'maPeriod', type: 'number', value: 20, min: 5, max: 100, step: 1 },
    ],
    indicators: ['SMA'],
    createdAt: '2024-05-20',
    updatedAt: '2024-05-20',
    status: 'active',
  },
  {
    id: 'buy_sell_market',
    name: 'Buy/Sell Market',
    description: 'A simple strategy that places immediate market orders to buy or sell an asset.',
    type: 'custom',
    parameters: [],
    indicators: [],
    createdAt: '2024-05-20',
    updatedAt: '2024-05-20',
    status: 'active',
  },
  {
    id: 'strategy_110',
    name: 'Strategy 110',
    description: 'A generic strategy with unknown parameters, likely for testing or future definition.',
    type: 'custom',
    parameters: [],
    indicators: [],
    createdAt: '2024-05-20',
    updatedAt: '2024-05-20',
    status: 'inactive',
  },
];

// Mock backtest results
export const mockBacktestResults: BacktestResult[] = [
  {
    id: '1',
    strategyId: '1',
    strategyName: 'Moving Average Crossover',
    symbol: 'AAPL',
    timeframe: '1d',
    startDate: '2023-01-01',
    endDate: '2023-12-31',
    initialBalance: 10000,
    finalBalance: 12500,
    roi: 25.0,
    maxDrawdown: 8.2,
    sharpeRatio: 1.3,
    winRate: 65,
    trades: 42,
    createdAt: '2024-04-01',
  },
  {
    id: '2',
    strategyId: '2',
    strategyName: 'RSI Overbought/Oversold',
    symbol: 'MSFT',
    timeframe: '1d',
    startDate: '2023-01-01',
    endDate: '2023-12-31',
    initialBalance: 10000,
    finalBalance: 11200,
    roi: 12.0,
    maxDrawdown: 6.5,
    sharpeRatio: 0.9,
    winRate: 58,
    trades: 35,
    createdAt: '2024-04-02',
  },
];

// Check if we're in development mode
export const isDevelopment = false;